config/routes.rb
Rails.application.routes.draw do
  resources :hitlists
  get 'home/index'
  get 'home/about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hitlist.rb
class Hitlist < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hitlists_controller.rb
class HitlistsController < ApplicationController
  before_action :set_hitlist, only: %i[ show edit update destroy ]

  # GET /hitlists or /hitlists.json
  def index
    @hitlists = Hitlist.all
  end

  # GET /hitlists/1 or /hitlists/1.json
  def show
  end

  # GET /hitlists/new
  def new
    @hitlist = Hitlist.new
  end

  # GET /hitlists/1/edit
  def edit
  end

  # POST /hitlists or /hitlists.json
  def create
    @hitlist = Hitlist.new(hitlist_params)

    respond_to do |format|
      if @hitlist.save
        format.html { redirect_to hitlist_url(@hitlist), notice: "Hitlist was successfully created." }
        format.json { render :show, status: :created, location: @hitlist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hitlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hitlists/1 or /hitlists/1.json
  def update
    respond_to do |format|
      if @hitlist.update(hitlist_params)
        format.html { redirect_to hitlist_url(@hitlist), notice: "Hitlist was successfully updated." }
        format.json { render :show, status: :ok, location: @hitlist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hitlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hitlists/1 or /hitlists/1.json
  def destroy
    @hitlist.destroy

    respond_to do |format|
      format.html { redirect_to hitlists_url, notice: "Hitlist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hitlist
      @hitlist = Hitlist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hitlist_params
      params.require(:hitlist).permit(:primer_nombre, :primer_apellido, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hitlists_helper.rb
module HitlistsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/hitlists/_form.html.erb
<%= form_with(model: hitlist) do |form| %>
  <% if hitlist.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(hitlist.errors.count, "error") %> prohibited this hitlist from being saved:</h2>

      <ul>
        <% hitlist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :primer_nombre, style: "display: block" %>
    <%= form.text_field :primer_nombre %>
  </div>

  <div>
    <%= form.label :primer_apellido, style: "display: block" %>
    <%= form.text_field :primer_apellido %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/hitlists/_hitlist.html.erb
<tbody>
    <tr>
      <td><%= hitlist.primer_nombre %></td>
    </tr>

    <tr>
      <td><%= hitlist.primer_apellido %></td>
    </tr>

    <tr>
      <td><%= hitlist.email %></td>
    </tr>

    <tr>
      <td><%= hitlist.phone %></td>
    </tr>

    <tr>
      <td><%= hitlist.twitter %></td>
    </tr>
</tbody>

app/views/hitlists/edit.html.erb
<h1>Editing hitlist</h1>

<%= render "form", hitlist: @hitlist %>

<br>

<div>
  <%= link_to "Show this hitlist", @hitlist %> |
  <%= link_to "Back to hitlists", hitlists_path %>
</div>

app/views/hitlists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Hit List</h1>
<h2>Shut the Fuck Up</h2>



<table class="table">
  <thead>
    <tr>
      <th>Primer Nombre</th>
      <th>Primer Apellido</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th colspan=3></th>
    </tr>
  </thead>
</table>

<tbody id="hitlists" class="table">
  <% @hitlists.each do |hitlist| %>
    <%= render hitlist %>
  <% end %>
</tbody>

<%= link_to "New hitlist", new_hitlist_path %>

app/views/hitlists/new.html.erb
<h1>Add a new target</h1>

<%= render "form", hitlist: @hitlist %>

<br>

<div>
  <%= link_to "Back to hitlists", hitlists_path %>
</div>

app/views/hitlists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @hitlist %>

<div>
  <%= link_to "Edit this hitlist", edit_hitlist_path(@hitlist) %> |
  <%= link_to "Back to hitlists", hitlists_path %>

  <%= button_to "Destroy this hitlist", @hitlist, method: :delete %>
</div>

app/views/home/_header.html.erb
<br/>
<br/>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<%= link_to 'HELL IS OTHER PEOPLE', root_path, class:"navbar_class" %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item">
        <%= link_to "About Us", home_about_path, class:"nav-link"%>
    </li>

    <li class="nav-item">
      <%= link_to "Show Hitlist", hitlists_path, class:"nav-link" %>
    </li>

    <li class="nav-item">
      <%= link_to "New Target", new_hitlist_path, class:"nav-link"%>
    </li>

    <li class="nav-item active">
      <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Link</a>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Dropdown
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">Something else here</a>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
    </li>
  </ul>
  <form class="form-inline my-2 my-lg-0">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
</div>
</nav>

<br/>
<br/>

<div class="container">
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
HELL IS OTHER PEOPLE</br>
</div>

<br/>
<br/>

app/views/home/about.html.erb
<h1>Sobre Nosotros</h1>

<p>Schizophrenic, euphoric scum</p>

app/views/home/index.html.erb
<p>Find me in app/views/home/index.html.erb</p>

<p>Lo mas importante es la capacidad de un programa es hacer la mayor cantidad de trabajo
posible. Entendiendo las maquinas en el modelo de los tres estados de la informacion, lo mas
importante es la capacidad de un programa de ejecutar la mayor cantidad posible de procesamiento.
</p>

<p>Se pueden escribir instrucciones para un computador</p>
<p>Se pueden escribir informes para personas</p>

<p>Que clase de universo es este.</p>
<p>Tal vez simplemente estoy furioso</p>

<p>Se pueden expresar ideas en formulas. Conocimiento declarativo. Aquello que es. En el conocimiento declarativo, el procesamiento corre por cuenta de las personas</p>
<p>El conocimiento declarativo es la base sobre la que se construye el conocimiento imperativo. El conocimiento de ejecutar acciones y obtener resultados concretos.</p>
<p>Existe nomenclaturas declarativas y nomenclaturas imperativas</p>
<p>Burning desire</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Hell is other people</title>
  </head>
  <body>
    <h1>Hell is other people</h1>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->

    <%= render 'home/header'%>
    <div class="container">
      <%= yield %>
    </div>

    <div class="container">
      <code>El codigo existe tal y como existen las jugadas de ajedrez sobre un tablero</code>
      <br>
      <code>Afectando solo una entidad el alcance se maximiza gracias a los principios de la programacion</code>
      <br>
      <code>Un modelo de negocios esquizofrenico</code>
      <br>
      <code>Nipple Alert</code>
      <br>
      <code>Gland Alert</code>
    </div>
  </body>
</html>